meta_product_name: "bound"
meta_title: "bound - don't watch, act!"
meta_description: "Envie de vous engager ? Participez facilement à des missions de bénévolat en rejoignant des associations près de vous !"
meta_image: "bound.jpg"
twitter_account: "@vansupernova"
